FROM amazoncorretto:17

ARG IMAGGA_API_KEY
ENV IMAGGA_API_KEY=$IMAGGA_API_KEY

ARG IMAGGA_API_SECRET
ENV IMAGGA_API_SECRET=$IMAGGA_API_SECRET

ARG DB_URL
ENV DB_URL=$DB_URL

WORKDIR /app

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8000

ENTRYPOINT ["java", "-jar", "app.jar"]
