#spring:
#  mvc:
#    hidden-method:
#      filter:
#        enabled: true
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8000