spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: 'ALL'
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: TRUE
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    generate-ddl: true
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
