name: Build and Analyze
run-name: Build and Analyze
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
        with:
          build-root-directory: ics-server

      - name: Build with Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          build-root-directory: ics-server
          arguments: build -x test sonar

      - name: Test with Gradle
        env:
          IMAGGA_API_KEY: ${{ secrets.IMAGGA_API_KEY }}
          IMAGGA_API_SECRET: ${{ secrets.IMAGGA_API_SECRET }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DELETE_KEY: ${{ secrets.DELETE_KEY }}
          BYPASS_THROTTLE_KEY: ${{ secrets.BYPASS_THROTTLE_KEY }}
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: test
          build-root-directory: ics-server

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          build-root-directory: ics-server
          name: ics-artifact
          path: build/libs