name: Docker
on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
  DOCKER_REPOSITORY_NAME: ${{ secrets.DOCKER_REPOSITORY_NAME}}
jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build Docker Image
        run: docker build . --file Dockerfile --platform linux/amd64 --tag $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY_NAME:${{ steps.date.outputs.date }}
      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY_NAME:${{ steps.date.outputs.date }}
